name: "bluebell"
mode: "dev"
port: 8080
version: "v0.0.1"
start_time: "2024-09-19"
machine_id: 1

log:
  level: "debug"
  filename: "web_app.log"
  max_size: 200
  max_age: 30
  max_backup: 7

mysql:
  host: localhost
  port: 3306
  user: "root"
  password: "2001010318"
  dbname: "bluebell"

redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
  db: 0
  pool_size: 100